py_binary(
  name = "friday_night",
  deps = [],
  srcs = ["friday_night.py"],
  deps = [
    
  ]
)
py_library(
  name = "friday_night_lib",
  deps = [],
  srcs = ["friday_night.py"],
  args = ["--drink"]
)